### ISSUE TITLE
Tbr is set to 0 by either internal driver or by user but in pod history when refreshed immediately after tbr is set, it shows other values

### ISSUE THREAD

**Issue by Kaivish** [AAPS-Omnipod/AndroidAPS-OLD#100]
Noticed that late at night. Posting pic of  pod history. I didnt listen to pod if it actually is 0.0u/hr or as what the pod history says. But swiping up and down in the pod history make the values/description at pod status change. Sometime 0.8, 0.1, 0.3u with duration 30 min. All that without changing the tbr ( which is still at 0.0u/hr according to home tab and pod tab) Not sure if basal is really suspended or just pod history is faulty. 

![IMG_20200229_013515](https://user-images.githubusercontent.com/41928579/75610497-e2734c00-5b11-11ea-88a8-11ba9dd5a6a0.jpg)
[AndroidAPS_LOG_1582931921452.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4270532/AndroidAPS_LOG_1582931921452.log.zip)

EDIT..... GUI BUG. checked pod if it clicks on tbr 0.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by andyrozman** [comment]
This is UI problem... Its fixced in 0.3

**Comment by mistermintsgh** [comment]
I don't know if this is related, or if it's anything I should be worried about, (and I'll raise a separate issue if needed @andyrozman ) but like in the above screenshots I am getting lots of "Cancel TBR (Forced by user)" messages when I did no such thing.

There are plenty which say it was cancelled by the driver which makes me wonder whether it is a system issue

![Screenshot_20200304-084846_AndroidAPS](https://user-images.githubusercontent.com/42671801/75867391-71c47c00-5dfe-11ea-807f-fe83e8e2b77c.jpg)
