### ISSUE TITLE
Cant see Omnipod as a pump option

### ISSUE THREAD

**Issue by reager** [AAPS-Omnipod/AndroidAPS-OLD#103]
My bad, didnt read all the instructions.  Please close this issue

I have cloned the repository (omnipod_eros branch) and built the project in Android Studio. When Im running it on my phone I do not see the omnipod option when Im supposed to select pump.

Build: EROS_0.2

**Comment by biwhite** [comment]
Turn on engineering_mode

**Comment by rajid** [comment]
I have followed instructions here:
https://readthedocs.org/projects/androidaps-altguide/downloads/pdf/latest/
and created the needed file "engineering_mode" under
Android->data->info.nightscout.androidaps->files
and have restarted the phone. 
Yet, it still doesn't show Omnipod as a pump choice.

When I built this version, I made sure my git branch was set to "omnipod_eros" under VCS->git branches.
