### ISSUE TITLE
Suspended pod in Open Loop-mode without error "No active pod"

### ISSUE THREAD

**Issue by Ljuslykta** [AAPS-Omnipod/AndroidAPS-OLD#104]
Twice, I've had the problem that without user input or indication from the app, the pod becomes suspended and a warning that there's no active pod. When looking in the RL tab, the "Last connected" is red, and when communication is refreshed the pump goes out of suspended and delivers insulin once again. 

The issues were discovered around the time I took screenshots, see the clock there for time.

Build version: EROS_0.2-2020.03.06-22:12
[AndroidAPS_LOG_1583936382490.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4325849/AndroidAPS_LOG_1583936382490.log.zip)
[AndroidAPS_LOG_1584005284203.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4325851/AndroidAPS_LOG_1584005284203.log.zip)

**Comment by Ljuslykta** [comment]
![Screenshot_20200312_102739_info nightscout androidaps](https://user-images.githubusercontent.com/13408877/76556949-cde06d80-649a-11ea-9804-898e6826390b.jpg)
![Screenshot_20200311_150921_info nightscout androidaps](https://user-images.githubusercontent.com/13408877/76556953-cf119a80-649a-11ea-8cc6-ce9f1f9e6374.jpg)
![Screenshot_20200312_102729_info nightscout androidaps](https://user-images.githubusercontent.com/13408877/76556955-d042c780-649a-11ea-9f9a-eede0f278507.jpg)

**Comment by bartsopers** [comment]
These issues have been fixed in the upcoming 0.4 release.
