### ISSUE TITLE
FEATURE REQUEST: Pod on body location log

### ISSUE THREAD

**Issue by mistermintsgh** [AAPS-Omnipod/AndroidAPS-OLD#105]
An idea to "borrow" a feature from the new Omnipod Dash PDM, and log the location of pods on the body so a user can track most recent infusion sites and more effectively rotate these to get better insulin sensitivity, reduce the chance of lumpy fat build up under the skin.

Details on what that looks like for Dash are located in the Dash manual on page 45 here:
https://www.myomnipod.com/sites/default/files/media/documents/18296-ENG-AW%20Rev%20B_USA%20DASH%20User%20Guide.pdf

**Comment by bartsopers** [comment]
@mistermintsgh we're not planning to add this in the Omnipod driver. I'd be happy to review a PR if anyone else wants to implement this though.
