### ISSUE TITLE
AAPS-Omnipod is showing wrong version tag?

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#108]
AndroidAPS 2.7-omnipod-0.3-SNAPSHOT
Build EROS_0.2-341-g8c803f7e0

**Configuration:**
-Local AAPS profile

**Problem:**

AAPS-Omnipod about shows correct version "2.7-omnipod-0.3"
My build is still showing "EROS_**0.2**-...."?

*Additional remark:**
Android Studio 3.6.1 (Windows 10)
Updated "omnipod_eros" branch to latest commit 8c803f7e using "pull"

![Screenshot_20200315-142032_AndroidAPS](https://user-images.githubusercontent.com/45144129/76702278-dcac6780-66c8-11ea-91da-a4c4f41d1462.jpg)

**Comment by andyrozman** [comment]
Fixed.
