### ISSUE TITLE
UI Redundant info text

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#109]
AndroidAPS 2.7-omnipod-0.3-SNAPSHOT
Build EROS_0.2-341-g8c803f7e0

**Configuration:**

- Local AAPS profile

***UI Look&Feel:***

- While executing a manual bolus AAPS-Omnipod shows a pop-up showing redundant info:
*--> Going to deliver X.XXU*
*Delivering X.XXU*

(The first message is a bit strange as it is not "stateless" and almost immediately outdated once "Going to" has started ;-)

(Suggestion: Change "Going to deliver" with "Executing bolus: ")

![Screenshot_20200315-100457_AndroidAPS](https://user-images.githubusercontent.com/45144129/76701961-45461500-66c6-11ea-9c1c-d57c24cccdd1.jpg)

**Comment by andyrozman** [comment]
Core code, closing
