### ISSUE TITLE
Deactivating failed, "Cancel" button greyed out?

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#110]
AndroidAPS 2.7-omnipod-0.3-SNAPSHOT
Build EROS_0.2-341-g8c803f7e0

Configuration:

**Message confusing:**
Deactivating failed due to Pod being expired. Message suggests to press "Cancel" but the button is greyed out. Because the Pod was already removed?

*Additional remark:*
Used phone's "page back", then selecting "Pod Reset" (was not actually required in this state?)
From there no problem using "Pod Init" to successfully initialize a new Pod.

![Screenshot_20200315-090649_AndroidAPS](https://user-images.githubusercontent.com/45144129/76702010-a837ac00-66c6-11ea-9784-b77c84f4e2f0.jpg)

[AndroidAPS_LOG_1583969831409.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4334234/AndroidAPS_LOG_1583969831409.log.zip)

**Comment by bartsopers** [comment]
You can use the back button on your phone to cancel.
Closing this for now as we don't intend to make any changes to the current Pod activation/deactivation wizards. Instead, we intend to create a new version of the Wizard in the future (please refer to issue #147)
