### ISSUE TITLE
Unable to Init Pod 

### ISSUE THREAD

**Issue by bionictom** [AAPS-Omnipod/AndroidAPS-OLD#112]
After first installing AAPS Eros 0.3 I couldn't Init pod, the option was greyed out. I restarted AAPS but nothing changed.

Everything worked after I rebooted my phone.

The succesful priming was at 18:48, so the problem occurred before that. I attached the log.

[AndroidAPS_LOG_1584309245311.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4335214/AndroidAPS_LOG_1584309245311.log.zip)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by teleriddler** [comment]
This may be linked to issue #125 and the latest dev 0.4 build has a lot of fixes that addressed and fixed that issue.

You might try building with dev to see if your issue has been resolved.

**My current setup:**

**Version:** 0.4 (AndroidAPS 2.7-omnipod-04.-dagger-SNAPSHOT)
**Build:** EROS_0.2-978-gd446751db-2020.08.06-22:15) 

**Phone:**  Samsung Galaxy S7 Edge, Android 8.1 (Oreo)
**RileyLink** (Firmware BLE113: ble_rfspy 2.0, CC110: subg_rfspy 2.2)
**xDrip+ Version:** Nightly build
**CGM:** Libre 2 with LibreView patched app 2.3

**Comment by bartsopers** [comment]
Will be fixed in #134
