### ISSUE TITLE
Action tab does has no option to switch APS "offline"

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#114]
AndroidAPS 2.7-omnipod-0.3-SNAPSHOT
Build EROS_0.2-341-g8c803f7e0

Configuration:
-Local AAPS profile

Problem:
Action/Care portal tab no longer offers an option to switch the APS "offline".

![Screenshot_20200316-082102_AndroidAPS](https://user-images.githubusercontent.com/45144129/76733530-47a97d00-6761-11ea-9383-a723488bac2d.jpg)

**Comment by andyrozman** [comment]
Reopen this is Core product
