### ISSUE TITLE
Pod initialization fails on first try with communication error - retries needed

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#115]
AndroidAPS 2.7-omnipod-0.3-SNAPSHOT
Build EROS_0.2-341-g8c803f7e0

*Configuration:*
Samsung S7 (SM-G930F), 
OS: Android 8.0.0 (latest updates Jan 8 2020)
xDrip+/FSL
Dedicated phone with only a few necessary apps installed.

**Problem**
Pod initialization fails on first try with communication error.
Retry eventually results in successful activation.

**Additiona remark**
For version V0.2 Pod initialization has been flawless every time.
Since upgrading to V0.3 _all Pod initializations_ failed at first try, needing at up to 3 retries before initialization could be executed successfully.

* Setup did not change, no OS updates applied since upgrading to V0.3
* I can not see any reason that could cause comm errors. On PodInit I keep RL and Pod next to each other as usual.

Time of event (logfile)
00:31:28.866 -> Start pair and prime, from there find "RileyLink reports timeout"

[AndroidAPS_LOG_1583969831409.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4364396/AndroidAPS_LOG_1583969831409.log.zip)

**Comment by andyrozman** [comment]
There were no communication changes (low level ones) in code from 0.2 to 0.3...
