### ISSUE TITLE
adjust color threshold for res indicator 

### ISSUE THREAD

**Issue by iampickle** [AAPS-Omnipod/AndroidAPS-OLD#118]
![1](https://user-images.githubusercontent.com/43931318/78808039-2a18ad80-79c5-11ea-8d8e-c8da89669ed7.jpg)

I've noticed that the res-indicator on my home screen is always yellow to warn me that the reservoir is low in my pod. Since the pod only gives accurate res reading after it is under 50units I would consider adjusting the threshold of the res indicator, so that it is yellow when there're only 50units in the res left.

**Comment by haspden** [comment]
@CommandMaster that is configurable in your own plugin preferences...

Home Screen > Top Rigt 3 dots > Plugin Preferences > Advances Settings >
Now adjust your Threshold Warning Reservoir Level [U] to 49 or lower (depending on your preference)

![image](https://user-images.githubusercontent.com/4039041/79453352-81c8a180-7fe1-11ea-87f5-5d97cc9b9cdc.png)

**Comment by haspden** [comment]
@andyrozman perhaps this issue should be closed now ?

Thanks as always

Henry

**Comment by iampickle** [comment]
thank you
