### ISSUE TITLE
Add ability to configure beeps

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#12]

**Comment by bartsopers** [comment]
Prepared `OmnipodManager` and `AapsOmnipodManager` for configurable beeps in b186f01c11c6b2f2aed9d75802228ef0254a2d61
TODO:
* Add settings for bolus, SMB, and basal beeps in UI (e.g. 3 checkboxes). They should all be enabled by default (for now).
* Return the value of these settings in the `AapsOmnipodManager.isBolusBeepsEnabled()`, `AapsOmnipodManager.isSmbBeepsEnabled()` and `AapsOmnipodManager.isBasalBeepsEnabled()` methods

**Comment by andyrozman** [comment]
Done, closing
