### ISSUE TITLE
Bolus started but missing 

### ISSUE THREAD

**Issue by illanz** [AAPS-Omnipod/AndroidAPS-OLD#123]
AAPS omnipod 2.7 - 0.3
I've launched a bolus for 90gr of carb / 10 units through the calculator. The orange progress bar has started, here are the pictures 20 minutes later : zero active insulin and zero carb from the bolus.
Now I'm unable to know if I had my insulin or not (I ate a pizza...)

Log is available (very long - should I post it here?) 
![IMG_20200425_194216](https://user-images.githubusercontent.com/60227881/80288065-a33e3180-8735-11ea-9ebc-e6b314219a10.jpg)
![Screenshot_2020-04-25-19-42-32-862_info nightscout androidaps](https://user-images.githubusercontent.com/60227881/80288067-a46f5e80-8735-11ea-9b2e-7168513e7bf1.png)
![Screenshot_2020-04-25-19-54-50-433_info nightscout androidaps](https://user-images.githubusercontent.com/60227881/80288068-a46f5e80-8735-11ea-9456-273f2a39d476.png)
![Screenshot_2020-04-25-19-44-07-097_info nightscout androidaps](https://user-images.githubusercontent.com/60227881/80288069-a46f5e80-8735-11ea-8564-ad62c38bffc8.png)

**Comment by bartsopers** [comment]
Can you please attach the log in a file? And do you remember at what time the bolus started?

**Comment by illanz** [comment]
Bolus was started at +/- 12:15 ~ 12:20
On the screenshots, it corresponds to 19:15 due to time shift
Here is the full log

**Comment by illanz** [comment]
[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4553760/AndroidAPS.log)

**Comment by andyrozman** [comment]
This could also be Wear issue...

**Comment by illanz** [comment]
How?
I did launch from the app and the orange bar started...

**Comment by bartsopers** [comment]
I looked at you log. I found very little communication with the Pod in the log, actually only 1 TBR command. As there's also no reproduction steps, there's not much I can do, so I'm closing this issue. If this happens again, please open a new issue and make sure to include the correct logs.
