### ISSUE TITLE
Omnipod_eros_dev 0.4: Pod address lost and "Communication failed: the Pod is in a wrong state"

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#126]
AndroidAPS 2.7-omnipod-0.4-dagger-SNAPSHOT
BuildVersion: EROS_0.2-973-g19675b195-2020.05.23-11:33

## Configuration: ##
Samsung S7, xDrip+

Additional remark:
With previous EROS versions tested, this phone showed no issues at all with connecting RL or communications.

## Problem description ###

AAPS looses Pod address on restart?
See also "In short: Repro steps" towards the end of this issue.

## Testing omnipod_eros_dev 0.4 ##

*Upgrad from latest 0.3 omnipod_eros_test commit with active POD1.*
AAPS was unable to communicate with the Pod: "Communication failed: the Pod is in a wrong state"

Attached:
        * Logfiles
        * Screenshots

Remark: please note the logfile errors:
__Illegal setup progress: null, expected: PRIMING_FINISHED__

## Steps taken: ##

Remark: Result form the test steps below can be consistently reproduced.

#### Export settings, Uninstall 0.3, Install 0.4 ####

	1. Open AAPS
	2. Setup Wizard
	3. Imports settings (old format)
	4. Close/exit AAPS
	5. Enable engineering mode

	1. Open AAPS
	2. Select xDrip+ as BG source
	
        POD1:
        - Reports "READSTATUS: Pump driver changed"
        - RL not started, Pod status: Not initialed.
        - Refresh button greyed out
        - Pod history: empty
        - RL status: Connected, but Pump Serial Number shows "??"

#### 14:56h: Forced stop, then restart ####

        POD1:
        Now shows "Connected (with original status info from 0.3?)
        - RL now reports the active Pod's serial number. Refresh button enabled...
        - No response on "Refresh".
        - Pod history now shows one entry: "Communication failed: the Pod is in a wrong state"

        Try bolus command:
        - Bolus delivery error Mute/Ok error
        - Pod history has now 2 additional error entries for "Communication failed: the Pod is in a wrong state" (on set TB, set Bolus)

#### Restart phone ####

        Identical behaviour.

## Logfiles ##

[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4671856/AndroidAPS.zip)

## Screenshots ##
![Screenshot_20200523-145348_AndroidAPS](https://user-images.githubusercontent.com/45144129/82732432-70279780-9d0d-11ea-9bb1-4e3351977437.jpg)

![Screenshot_20200523-145343_AndroidAPS](https://user-images.githubusercontent.com/45144129/82732431-6f8f0100-9d0d-11ea-817a-4c71167db653.jpg)

![Screenshot_20200523-150421_AndroidAPS](https://user-images.githubusercontent.com/45144129/82732429-6ef66a80-9d0d-11ea-87d5-04cf5af661d9.jpg)

![Screenshot_20200523-150035_AndroidAPS](https://user-images.githubusercontent.com/45144129/82732427-6e5dd400-9d0d-11ea-8859-1fd0e867516c.jpg)

![Screenshot_20200523-150026_AndroidAPS](https://user-images.githubusercontent.com/45144129/82732426-6dc53d80-9d0d-11ea-898e-297666daf597.jpg)

**Comment by vanelsberg** [comment]
### Tested activating a new Pod. ###

De-activating the current active Pod resulted in a "Communication failed: the Pod is in a wrong state" error.

The _"Reset Pod"_ option took care of that.
From there activating a new Pod was as usual - no problems.
RL Comms also seem to be stable as usual.

_Until after some 30mins I lost the RL connection (see next comment below):
Started getting "Communication failed: the Pod is in a wrong state" errors again..._

#### POD2: ####
Lot: 45387 (serial)
tid: 0921071
Pod address: 520274285
POD: L45387, 0921071


### Logfiles ###
Logfile as created after installation, Resetting the active Pod and activating a new Pod:

[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4672537/AndroidAPS.log)

### Screen shots ###
![Screenshot_20200523-224214_AndroidAPS](https://user-images.githubusercontent.com/45144129/82740815-86a11380-9d4c-11ea-813c-9ef18aa21ae1.jpg)

![Screenshot_20200523-224441_AndroidAPS](https://user-images.githubusercontent.com/45144129/82740817-8acd3100-9d4c-11ea-9f6d-cd981675396e.jpg)

![Screenshot_20200523-224451_AndroidAPS](https://user-images.githubusercontent.com/45144129/82740819-93256c00-9d4c-11ea-8477-566234c1d6f5.jpg)

![Screenshot_20200523-224457_AndroidAPS](https://user-images.githubusercontent.com/45144129/82740823-9ae51080-9d4c-11ea-8d3b-56b2cec6378f.jpg)

![Screenshot_20200523-224756_AndroidAPS](https://user-images.githubusercontent.com/45144129/82740827-9e789780-9d4c-11ea-9f51-2640d4653e95.jpg)

**Comment by vanelsberg** [comment]
## Problem not solved ##

Lost connection to RL while going for coffee, leaving RL on my Desk....

RL reconnected without problems, including POD2 serial, but now communication to the Pod is back to _"the Pod is in a wrong state"._ So this is the exact same situation I had when trying to take over an active Pod when upgrading to 0.4....

_I would say there is definitely a problem met omnipod_eros_dev_

Will downgrade to V0.3 after adding the logs below

### Logfiles ####

[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4672605/AndroidAPS.log)

[AndroidAPS._2020-05-23_23-56-22_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4672604/AndroidAPS._2020-05-23_23-56-22_.1.zip)

[AndroidAPS._2020-05-23_23-56-22_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4672606/AndroidAPS._2020-05-23_23-56-22_.0.zip)

**Comment by vanelsberg** [comment]
Uninstalled 0.4 and installed 0.3
Imported v0.3 settings.

Surprise: AAPS started communicating with POD2 (activated with 0.4).
How is that possible as the POD in settings was de-activated/expired? 
AAPS also starts complaining about the POD2 being expired and after some time errors out on POD is expired responses.
_De-activation of POD2 (with v0.3!!!) was succesfull_

Activated new POD3 with v0.3 and all as well
POD3:
AAPS.Omnipod.pod_state->
"lot":45387   (serial)
"tid":1010977
"address":520739593
POD: L45387, 1010977


[AndroidAPS._2020-05-24_02-58-39_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4673443/AndroidAPS._2020-05-24_02-58-39_.0.zip)
[AndroidAPS._2020-05-24_03-13-58_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4673444/AndroidAPS._2020-05-24_03-13-58_.0.zip)
[AndroidAPS._2020-05-24_03-13-58_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4673445/AndroidAPS._2020-05-24_03-13-58_.1.zip)
[AndroidAPS._2020-05-24_13-22-16_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4673446/AndroidAPS._2020-05-24_13-22-16_.0.zip)
[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4673447/AndroidAPS.zip)
[AndroidAPS._2020-05-24_02-49-30_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4673448/AndroidAPS._2020-05-24_02-49-30_.0.zip)

**Comment by vanelsberg** [comment]
Do not get it, does not make sense. In a nutshell, what is looks like (just guessing).
I would say V0.4 messes up with the Pod address.
Programming and initially successfully using the  Pod address of the previous Pod address (but storing a the new). On restart it switches to the new pod address which is not the address that was programmed to the Pod?

### Observations: ###

1. Upgrading form v0.3 to V0.4: fails (is AAPS somehow using the wrong Pod address?)

2. On V0.4 the Pod is reset. Activate new Pod initially is successful but AAPS looses the Pod address on app restart. Does it maybe program and initially use the old Pod address of the de-activated Pod (see2)? Then on restart, the new Pod address stored obviously does not work on the new Pod?

3. Downgrading to original V0.3 still has the old Pod Address of the expired Pod in settings,
However it can communicate with the newly activated Pod from v0.4?

**Comment by vanelsberg** [comment]
See also #111

**Comment by vanelsberg** [comment]
Additional comment:
This report , quite unexpectedly became a long story.
I guess it has to much information at once.

### In short: Repro steps: ###

1. While running an active Pod: export settings, uninstall V0.3 and install V0.4, import settings.
2. Deinit the active Pod (which is erroring "wrong state"). Activation should be successful.
3. Activate new Pod. PodInit should be successful, Pod is communication and OK.

DO NOT RESTART AAPS!
Verify AAPS and Pod are operating as expected.

4. Now restart AAPS. Pod starts erroring "wrong state". Unrepairable....
5. Uninstall V0.4 and reinstall V0.3, import original V0.3 settings.
6. _AAPS is communicating with active Pod (newly activated on 0.4!?)_

In my case the previous Pod from V0.3 was about to expire, so after initially communication with the Pod AAPS started complaining about the Pod being expired, then after a few minutes stopped working all together. Pod lost...

From there nothing wrong with the system for V03:
Activated a new Pod that worked for the full 80 hrs without any problems.
As usual, no comm errors.

**Comment by vanelsberg** [comment]
### I would suggest 2 test cases: ###

1. While on an active Pod: 
Export settings. Uninstall V0.3, Install V0.4, import settings.

2. Make sure there is no Pod activated on V0.3 (When necessary deactivate Current Pod first)
Then export settings, uninstall V0.3, Install V0.4, import settings.

For both situations, activate a new Pod. Conclude it is working just fine,
Then restart AAPS....

**Comment by vanelsberg** [comment]
#### Executed test case #2. ####
Same behavior: after initially activating the Pod successfully, lost communication after restarting AAPS, erroring "the Pod is in a wrong state".

#### Tried saving the newly activated Pod by capturing it with v0.3. That failed (with the same error) making me think the Pod address as exported by v0.4 json settings does not correspond to the actual Pod address? ####

(As the Pod was activated ok and responsive up until AAPSv0.4 restarted I find it unlikely  there is anything wrong with the Pod state...)_

**Comment by vanelsberg** [comment]
Looks related to issue #102?

**Comment by bartsopers** [comment]
Fixed :-)

**Comment by bartsopers** [comment]
Thank you for the extensive research & reproduction path @vanelsberg!

**Comment by vanelsberg** [comment]
Top! Thanks for solving this Bart! 
Will start testing this a.s.a.p.
