### ISSUE TITLE
OpenAPS SMB does not take Max IOB setting from preferences

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#138]
### Problem:

OpenAPS SMB Seems to ignore the Max IOB setting in preferences.
Under "constraints" it says "Safety: Limitting IOB to 3.0 U because of max value in preferences". 
Also "Profile:" lists "max_iob: 3.

#### Observations:
3.0 U seems fixed?
No matter what value I set as "Maximum basal IOB OpenAPS can deliver".
When selecting OpenAPS, "Profile:" does list the correct setting.

**Comment by vanelsberg** [comment]
Any relation to current branch/merge and/or EROS driver?
Or is maybe this AAPS related...

**Comment by vanelsberg** [comment]
[AndroidAPS_LOG_1597576169957.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5080543/AndroidAPS_LOG_1597576169957.log.zip)
![Screenshot_20200816-130853](https://user-images.githubusercontent.com/45144129/90332989-0e9c5f80-dfc2-11ea-8b16-d139f0008d41.png)
![Screenshot_20200816-130911](https://user-images.githubusercontent.com/45144129/90332990-0fcd8c80-dfc2-11ea-8858-93546e18ea4f.png)

**Comment by bartsopers** [comment]
I think this is a bug in the upstream dev version that we were using for 0.4. Closing for now, please re-report if this issue still exists after the 0.4 release.

**Comment by vanelsberg** [comment]
Yes..
Will re-report when still exists.

**Comment by vanelsberg** [comment]
Problem seems to be solved for AAPS 2.7-omnipod-0.4.1-SNAPSHOT
