### ISSUE TITLE
Omnipod tab is too far to the right

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#141]
The Omnipod tab is pretty far to the right, which is inconvenient as users should scroll horizantally to see the tab when they're in the overview.
Move the Omnipod tab closer to the left, like other Pump plugins.

**Comment by bartsopers** [comment]
Fixed

**Comment by vanelsberg** [comment]
@bartsopers I can not confirm this is fixed (running eros_dev commit 5d83e2a2 of 19/8)?
POD tab is still the last tab (right) on screen.
