### ISSUE TITLE
Improve set up wizard (?)

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#145]
Investigate whether the initial AAPS setup wizard needs improvement when selecting Omnipod

For example also see #52

**Comment by vanelsberg** [comment]
Tested AAPS 2.7-omnipod-0.4.1-SNAPSHUT (commit dc6c19fd) on Samsung Note 9 (Android OS 10):

In general installation Wizard could be completed successfully resulting in an operational AAPS setup for OmniPod.
Communicating with RL, no Pod activated.

* Need for additional documentation specific on installing/configuring for OmniPod (is this available?):
  User is expected to know how to configure RL and OmniPod....
  Hint: Even though the installer tries to configure for battery optimization,
  add additional warning user should validate the final result?

* Default settings for "status lights" configuration (e.g. insulin/battery age) make no sense for OmniPod?
  (User needs to update this afterwards)

**Comment by vanelsberg** [comment]
**Additional remark:**

Even though Nightscout configuration was successful I was unable to configure a NS profile (non showing - it should).
Could be a local problem: using local profile, never fully configured NS profile
Needs additional testing?

**Comment by vanelsberg** [comment]
Pod init for the test config executed: no issues or remarks.

**Comment by bartsopers** [comment]
When selecting Omnipod as a pump, the Next button doesn't appear. The next button is only enabled when the pump is ready to accept commands, which for Omnipod means that both a RL and a Pod should be paired. 
Discussed this with Milos and he prefers to force users to pair a Pod before allowing to continue the Setup Wizard, so I'll look into that.

**Comment by bartsopers** [comment]
Fixed this for now by allowing to continue Setup Wizard when a RileyLink connection has been established. Added additional future improvements to issue #147
