### ISSUE TITLE
On start, Pod status is wrong in overview page and Omnipod tab

### ISSUE THREAD

**Issue by andyrozman** [AAPS-Omnipod/AndroidAPS-OLD#15]
On start of AAPS, the pod status is wrongly displayed in both the Overview tab and the Omnipod tab:
* in the Overview tab, it says 'Pump suspended'. When navigating away to any other tab, and then navigating back to the Overview tab, the 'Pump suspended' warning disappears.
![Screenshot_20191207-133427](https://user-images.githubusercontent.com/15631208/70375002-883f6200-18f9-11ea-8fd7-d8f8c98ef3f2.png)
* In the Omnipod tab, it says 'Pod Status: Never contacted'. This can be updated by either clicking the refresh button on the Omnipod tab, or by executing any command (e.g. a bolus)
![Screenshot_20191207-133434](https://user-images.githubusercontent.com/15631208/70375000-84134480-18f9-11ea-8cb7-b0d9ff0b1a4e.png)

**Comment by bartsopers** [comment]
This is still an issue: the pump status is still (incorrectly) set to suspended during startup. When switching between tabs a few times, the "Pump suspended" warning on the overview tab disappears.
