### ISSUE TITLE
AAPS/RL not allways able to successfulle restore connectivity

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#158]
## AndroidAPS 2.7-omnipod-0.4.1-SNAPSHOT
Remote: https://github.com/AAPS-Omnipod/AndroidAPS.git
Flavor: fullrelease
Nightscout version: 0.12.3

Configuration:
Samsung S6/S7/S9, xDrip/FSL, Nightscout, AAPS local profile

### Problem:

Lost connection with the pump does not always restore.

#### This is a follow-up for issues #116:

The problems mentioned by this issue are resolved, with just one (imho) minor issue where AAPS gets in a state where the RL/Pump connection can not be restored successfully, resulting in a "Pump unreachable" alert

##### Repro:

    1. Get RL out of range from the phone for more then 10 minutes (hint: store it in a metal box)
    2. After 10 minutes get RL with range and see if it reconnects with successful communications.

    AAPS either restores or fail to restore the connection at this point.
    Reproducing the problem might need several tries?

##### Error behavior:

    1. AAPS POD tab and RL-stat claiming they are connected "Connected"
    2. Refresh button on POD tab has does not refresh state but also does not shows errors.
    3. Communication timeout errors when issuing commands.

Due to better handling of "pump unreachable" problems AAPS will issue a "Pump unreachable" alert.

To get AAPS out of this state:

    * Exiting through to "..." menu
    * Reopen AAPS

### Repro:
AAPS can get into this state when Phone and Pod get out of range of RL for a longer time (> 10 min)
On return within range, AAPS will try to restore connection but may fail. In case restoring fails AAPS gets into the "Connected" but "communication timeout errors" state as described.

    _Remark: did not try if version 0.4.1's "REST RILEYLINK CONFIG" has any effect here_

**Comment by bartsopers** [comment]
Closing this as we aim to fix this by implementing an auto-reconnect feature for the RileyLink as described in issue #150
