### ISSUE TITLE
Build naming "EROS_0.2" is confusing?

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#159]
### AndroidAPS 2.7-omnipod-0.4.1-SNAPSHOT
Remote: https://github.com/AAPS-Omnipod/AndroidAPS.git
Flavor: fullrelease
commit dc6c19fd

### Observation:
About is showing "Build: *EROS_0.2*-<id><build_datetime>"

Build naming "EROS_0.2" is confusing?
Expecting "EROS_0.4"?

**Comment by bartsopers** [comment]
The build number is auto-generated and this is implemented in AAPS core, which we're not going to change.
