### ISSUE TITLE
Reservoir level is sometimes set to incorrect values

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#16]
When the Pod's reservoir is over 50 units, sometimes it's incorrectly set to 75, and sometimes also the number 73 has been observed. We haven't yet been able to pinpoint when and why exactly this happens.

**Comment by andyrozman** [comment]
This is fixed. We don't subtract values if reservoirRemainingUnits is 0 or 75 (75 is predefined neutral value).
