### ISSUE TITLE
Upgrading a running 0.3 session to 0.4 without resetting active pod leads to confused pod state in 0.4

### ISSUE THREAD

**Issue by eurenda** [AAPS-Omnipod/AndroidAPS-OLD#162]
When upgrading from 0.3 to 0.4 with a running pod session and activating a new pod leads to old settings being migrated and an unclear state in AAPS.  Though  this is not a supported use case, users experiencing this will need to reset pod and restart AAPS 0.4 in order to clear ambiguous state.

**Comment by bartsopers** [comment]
We're not fixing this in code, but I think a good solution would be if someone would write upgrade instructions from 0.3 (or earlier) to 0.4, ideally with some clarifying screenshots.

**Comment by eurenda** [comment]
I'll add this to the issue to document and close it
