### ISSUE TITLE
Insulin delivery through bolus wizard (including timeshift) incorrectly registered by AAPS

### ISSUE THREAD

**Issue by Matthijsgr** [AAPS-Omnipod/AndroidAPS-OLD#163]
I'm not sure if I should post this here or in the MilosKozak/AndroidAPS branch, but here goes.

At 8.15 I used the bolus calculator for my breakfast (67 grams, AAPS suggested to bolus for 6,9 U). I entered a timeshift of 15 minutes as I wasn't going to eat right away. When delivery finished, AAPS didn't show an IOB, only the amount of carbs. It also wasn't visible under treatments. However, when pressing 'calc' in the treatments tab, it did show the amount of insulin delivered. Also NS registered the insulin correctly. This error always and only occurs when using a timeshift. 

![117404122_10219851037040537_1350405992885901792_o](https://user-images.githubusercontent.com/63582072/91725785-80b69c00-eb9f-11ea-8d71-3ffff439af66.jpg)
![117643620_10219851079961610_1386351374129220511_o](https://user-images.githubusercontent.com/63582072/91725789-814f3280-eb9f-11ea-9f82-63c042edaaba.jpg)
![117637040_10219858879996606_4371268686675973038_o](https://user-images.githubusercontent.com/63582072/91725790-814f3280-eb9f-11ea-8f79-448af7169b6e.jpg)

[AndroidAPS._2020-08-11_00-00-20_.0 (1).zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5150501/AndroidAPS._2020-08-11_00-00-20_.0.1.zip)

**Comment by vanelsberg** [comment]
Confirming.
I see this on version 2.7-omnipod-0.4.1-SNAPSHOT, Build EROS_0.2-1650-gac922316a,
Looks like AAPS is also treating the bolus as future insulin?

What I see:
* Bolus is administered right away, Carbs are registered in the future.
Even though the bolus was given it is not taken in account in IOB, both in the overview as in OpenAPS/SMB calculation.

* But eventually AAPS does register the bolus amount at the moment the carbs are "activated".
IOB in overview and with OpenAPS/SBM start showing the addition insulin from the past...

**Comment by vanelsberg** [comment]
Question: what is expected behavior?
Bolus insulin are both delayed and are calculated as such (what I expected),
Bolus is *not* delayed, cabs are. AAPS then should *not* delay the registration for IOB.

**Comment by vanelsberg** [comment]
One could argue it is unexpected (and potentially dangerous) behavior: either the bolus itself is delayed or it is immediately and should then also be registered as such. As is one could have more IOB for a longer period without AAPS acting on it.

**Comment by bartsopers** [comment]
Is there any documentation to support that this isn't (or is) expected behavior?

**Comment by vanelsberg** [comment]
Looks like https://github.com/MilosKozak/AndroidAPS/issues/2469 (?)

_no insulin in AAPS with future carbs_

**Comment by bartsopers** [comment]
@Matthijsgr Thank you for reporting this. I looked into the issue that @vanelsberg mentioned (thanks!) and that is indeed a similar problem caused by the same messy AAPS database implementation, so I added the same workaround for the Omnipod driver.

TL;DR: fixed
