### ISSUE TITLE
UI improvements in init pod dialogs

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#17]
When sending a command fails in the init pod dialogs, the Next button is disabled which only makes it possible to press the Cancel button. Pressing the cancel button then forcibly resets the pod state. A few improvements should be made in this is order to prevent users from discarding a lot of pods:
* When communication fails, the Next button should be replaced with a retry button, instead of being disabled.
* When the user presses the cancel button, the pod state should not be forcibly reset, because it will make the pod useless if an address has already been assigned (which is the first command of the init pod command sequence). If communication fails halfway through the init pod process, the OmnipodManager will remember the Pod's state which enables the init process to be completed later. 
* When the user presses the cancel button, the action should be confirmed with a dialog, like "Setting up the pod hasn't completed yet. Are you sure you want to cancel?"
* Currently, you can go back and forward in the init dialogs by swiping to the left or right. That should be disabled.
* If the podSessionState is not null when opening the init pod dialogs, implement a check: 
`if(podSessionState.getSetupProgress().isAfter(SetupProgress.PRIMING)) {`
then the first step should be skipped, and the user should directly go to the 'Insert cannula' dialog

**Comment by andyrozman** [comment]
Done
