### ISSUE TITLE
add acknowledgement message of profile switch from pod

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#22]
With AAPS with Combo, I get a message a few minutes after a profile switch, acknowledging that the profile in the pump has been updated. It would be nice if a similar message came from pod.

**Comment by bartsopers** [comment]
Thanks for reporting, we’ll look into this. Can you please add an example screenshot of the message you get with the combo?

**Comment by bartsopers** [comment]
Another possible solution for this would be to distinguish between basal and temp basal in beep configuration. 

You would always be notified when setting a basal schedule fails, so if you don't see an error message, you should know that it succeeded. You actually also rely on that for temp basals, as in general, these would be automatically set by AAPS, without any acknowledgement message to the user. 

If however you would like some extra confirmation specifically for basals, you could just enable the basal beeps (when we make a separate setting for temp basal beeps, which you could then disable).

**Comment by ZandMarc** [comment]
![Screenshot_20191215-175504](https://user-images.githubusercontent.com/31537397/71043585-5f0ba680-212f-11ea-85b3-a80714327823.png)
![Screenshot_20191215-175446](https://user-images.githubusercontent.com/31537397/71043588-62069700-212f-11ea-9ae9-8a7de00915c3.png)

**Comment by andyrozman** [comment]
Done. I added both notifications, if profile change is OK and if profile change fails...

**Comment by bartsopers** [comment]
@andyrozman these messages would also be very nice to have for the setTime command

**Comment by ZandMarc** [comment]
Did a profile switch tonight and got the notifications. Perfect! Thx, @andyrozman !
