### ISSUE TITLE
Field "last bolus" in Omnipod tab shows no value

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#27]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by bartsopers** [comment]
This is caused by storing the last bolus in AapsOmnipodManager, which is not persisted but recreated on app restart and such events.

TODO:
- store last bolus info in PodSessionState so it gets persisted
