### ISSUE TITLE
Field "serial number of pump" in RL stats tab has no value

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#28]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by andyrozman** [comment]
Are you sure? If you Inited pod correctly, then address of Pod should be displayed...

**Comment by ZandMarc** [comment]
![Screenshot_20191222-192951](https://user-images.githubusercontent.com/31537397/71325785-25052080-24f2-11ea-8302-bb879287b92f.png)

**Comment by ZandMarc** [comment]
Pod and rl are working fine. Still, address is not displayed and neither is the serial number of the pod

**Comment by vanelsberg** [comment]
Confirming!

**Comment by ZandMarc** [comment]
Tested: works for me!

**Comment by ZandMarc** [comment]
Tested: works for me!

**Comment by vanelsberg** [comment]
Commit 36128c40:
Tested: works for me!

**Comment by bartsopers** [comment]
As @ZandMarc and @vanelsberg  already noted: fixed by @andyrozman in 36128c4007d99aa882e821e30b94d9400fd3f67f
