### ISSUE TITLE
Add button to read pulse log in Omnipod tab

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#41]
Add a button to read pulse log in Omnipod tab.
Clicking it should call the AapsOmnipodManager.readPulseLog() method. The result (a PodInfoRecentHighFlashLogDump) should be shown (e.g. in a popup) and stored to a file. We can just use the PodInfoRecentHighFlashLogDump's toString implementation for that, for now.

This should also be possible when the Pod has a fault event (I suspect that that would currently already be the case).

**Comment by andyrozman** [comment]
This should be done now... Button is added with other 4, but only if configuration for it is enabled. 
Dialog used is error dialog, but let's keep it for now like that. At the same time dialog is opened, content is copied to clipboard.
