### ISSUE TITLE
UI issues in init pod dialogs

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#43]
In the init pod dialogs, when communication fails, there's a few UI issues:
- The checkboxes get checked, even though the commands failed
- The text is made red, but stays red when you press the retry button. At that point, the font should be reset to the default color.
- When you use the retry button, and then the command does succeed, the next button doesn't get enabled
- It it still possible to go back/forth between steps by swiping. That should be disabled.

**Comment by andyrozman** [comment]
Fixed, everything except swiping (and tested by Bart).
