### ISSUE TITLE
Last connection time incorrectly updated to Now after clicking refresh when pod is already deactivated

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#44]
I had a pod that had a pod fault and I deactivated it. However something went wrong there so AAPS still kept the pod state, but, the pod was actually successfully deactivated. However when I pressed the refresh button in the Omnipod tab, the last connection got updated to 'Now', but it's not possible that it had actually connected successfully to the pump

**Comment by andyrozman** [comment]
This should be fixed. Time is now updated only when command was successful.
