### ISSUE TITLE
Sometimes info in Omnipod tab "hangs"

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#46]
Sometimes the Omnipod tab seems to "stall". See screenshot attached: the  bolus of 3.6U mentioned after pod status, was ordered and delivered an hour before the screen shot. After that, several smb's were done. The "bolus of 4.4U, 52 min ago" was actually delivered almost 2 hrs before the screenshot.
![Screenshot_20191229-003146](https://user-images.githubusercontent.com/31537397/71558536-f688c780-2a54-11ea-8410-334fd1042a55.png)

**Comment by andyrozman** [comment]
Last bolus is meant for last "real" bolus. SMBs are ignored...

**Comment by ZandMarc** [comment]
That's different from how Combo tab behaves: there the last bolus shows the SMB's. But either way, that's not the point of this issue. This issue is about the bolus not "disappearing" from Pod status and "appearing" at Last bolus.

**Comment by andyrozman** [comment]
Why should it disapper? It shows last Bolus. SMBs are part of oRef1 and shouldn't be displayed here... I have sometimes last bolus there for 6 hours (since the last bolus)...

**Comment by ZandMarc** [comment]
I think it should be at the "Last bolus: " line, not hanging for hours at the "Pod status: " line

**Comment by andyrozman** [comment]
Oh you meant unser Pod Status? Mhm... That is queue, this core thing, there is nothing I can do about that, but that should go out as soon as command is finished... Does this happen often?

**Comment by ZandMarc** [comment]
Under pod status is what I meant, yes. I haven't kept track of it, but I think it happens a couple of times a day. I'll watch and keep track of it the next couple of days.

**Comment by ZandMarc** [comment]
I haven't seen this happen in the last days/weeks. I'll close the issue for now.
