### ISSUE TITLE
Text missing in "pair and prime" screen

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#47]
In the "pair and prime" screen, some text is missing. Probably because the spinner and checkboxes cover it.
![Screenshot_20191228-131209](https://user-images.githubusercontent.com/31537397/71558662-ef15ee00-2a55-11ea-9b3a-1318f1c5b394.png)

**Comment by ZandMarc** [comment]
The same goes for "deactivating the pod" screen. Text is cut off after "please press Cancel and use"...

**Comment by bartsopers** [comment]
I would personally (still) opt for removing the checkboxes and just show the spinner, as the checkboxes add no value for the user IMO. I feel that for the user, the only relevant thing is that the pairing and priming step succeeded, and not the individual steps like assigning an address. It might be useful for us devs, but we can already see that info in the logs.

Removing the checkboxes would save some space and possibly fix this issue.

**Comment by andyrozman** [comment]
You don't even see the second checkbox, or is that just problem with taking snapshot?

**Comment by ZandMarc** [comment]
I think the second checkbox is covered by the spinner (barely visible in the screenshot, but it's there). I second Barts suggestion to remove the checkboxes, since they don't add info to the user. They are either both unchecked or both checked, so they don't offer info on the progress of the process.

**Comment by andyrozman** [comment]
I changed fonts and sizes a little, so this should be fixed... Please reopen if its not fixed...

**Comment by andyrozman** [comment]
Is this fixed? @ZandMarc

**Comment by ZandMarc** [comment]
yes, this is fixed
