### ISSUE TITLE
After scanning for and selecting Rileylink, it isn't initialized

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#49]
After I have scanned for and selected an RL, AAPS doesn't initialize it. In the Omnipod tab it says "bluetooth connected" and the BT-symbol is spinning. Nothing further happens. After I forcefully stop AAPS and start it again, RL is initialized and connection to pod is made.
![Screenshot_20191229-153227](https://user-images.githubusercontent.com/31537397/71558844-cb53a780-2a57-11ea-8669-954bd567c825.png)

**Comment by andyrozman** [comment]
Yes we have some problem with Medtronic... After you select it for first time, you have to restart application. I could never got this working, and after few tries I haven't continued with it. Problem is that sometimes it works and sometimes it doesn't...

**Comment by ZandMarc** [comment]
Ok, something for the docs then.

**Comment by bartsopers** [comment]
Can anyone confirm this issue still exists?

**Comment by mistermintsgh** [comment]
> Can anyone confirm this issue still exists?

I get this issue (0.3)

**Comment by vanelsberg** [comment]
Not sure.
On one of @bartsopers early "trial commits" to find the cause of "loosing the Pod after restart", 
I experienced something similar after trying to switch to another RL.

Wil retest switching/initializing RL for the dev/0.4.1 build.

**Comment by bartsopers** [comment]
Closing this as I haven't received any reports of this behavior in omnipod_eros_dev. If you run into this issue again, please create a new issue.
