### ISSUE TITLE
Text in Insert canula is copy from prime

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#50]
In the "insert canula" screen, the text from "pair and prime" is copied
![Screenshot_20200101-121904](https://user-images.githubusercontent.com/31537397/71641068-de53bb00-2c95-11ea-81fc-372f74d273ea.png)

**Comment by bartsopers** [comment]
I also experienced this behavior. We should fix this before releasing the first test version

**Comment by andyrozman** [comment]
Fixed.
