### ISSUE TITLE
Text in deactivate isn't completely visible

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#51]
Adjusting the font fixed the issue of several texts in initpod windows being unreadable. Only the font in "deactivate" seems unchanged, resulting in the last line being slightly cut off on my small (4.6 inch) screen 
![Screenshot_20200104-130958](https://user-images.githubusercontent.com/31537397/71782071-38c28380-2fd6-11ea-8dc5-6ad50f13a9d8.png)

**Comment by andyrozman** [comment]
I made text area little bit smaller when I did the font change, but I can try to make little bit bigger... I am testing with relatively small phone (Samsung A5 (v1) = 5.0' screen, so I didn't think it will be a problem... 

I will make a change and you can test it (on branch), next week.

**Comment by andyrozman** [comment]
I made a change, please test both init AND deactivation and post pictures here so that I can see if its correct...

**Comment by andyrozman** [comment]
@ZandMarc Is this fixed?

**Comment by ZandMarc** [comment]
No. Just aesthetics though: Text is completely readable, only tails of p and y are cut off.

**Comment by bartsopers** [comment]
I also experience this on my Pixel 3a, which has a quite large screen. 
![Uploading Screenshot_20200113-091009.png…]()

**Comment by bartsopers** [comment]
I also experience this on my Pixel 3a, which has a quite large screen. (it's quite clear in the word 'option' in the last sentence in below screenshot)
![Screenshot_20200113-091009](https://user-images.githubusercontent.com/15631208/72689209-5253e700-3b0f-11ea-8183-e197f5dc9e30.png)

**Comment by andyrozman** [comment]
Is this still the problem?

**Comment by ZandMarc** [comment]
I updated apk Wednesday and will deactivate this weekend: I’ll check and let you know (and close the issue if it is)

**Comment by ZandMarc** [comment]
Better, but now I see there's another line, with 1 word ("state"?) That's not readable: see screenshot.
![Screenshot_deactivatescreen](https://user-images.githubusercontent.com/31537397/73136102-17d7d600-404a-11ea-960c-88da4a49f398.png)

**Comment by andyrozman** [comment]
Should be fixed now...
