### ISSUE TITLE
After pump setup in "setup wizard", "next" stays greyed out

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#52]
When using the setup wizard (e.g. after first install) and selecting Omnipod from the available pumps, there's the option to do pump setup. After doing that (mainly: scanning and selecting RL) and returning to that window of the setup wizard, the "next" option stays greyed out, making it impossible to properly finish the setup wizard.

**Comment by bartsopers** [comment]
CLosing this as I created a more general issue for improving the set up wizard.
