### ISSUE TITLE
Lot of (incorrect) Time and/or Timezone changed notification

### ISSUE THREAD

**Issue by Kywalh** [AAPS-Omnipod/AndroidAPS-OLD#55]
Twice a day at noon and midnight, the following  green notification appears: 

> Time and/or Timezone changed on the pump

![Screenshot_20200119-001912](https://user-images.githubusercontent.com/28366579/72678333-1dab4580-3aa5-11ea-9f23-d77949beb494.jpg)

**Comment by Kywalh** [comment]
#
[AndroidAPS._2020-01-18_13-10-47_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4082455/AndroidAPS._2020-01-18_13-10-47_.1.zip)

**Comment by andyrozman** [comment]
I added some logging here... I am testing this on separate application and I am not noticing any time changes... (someone said he got changes at least every 12 hours)... So far I haven't seen anything... 

There will be log in AAPS from now on, so we can follow this problems

**Comment by Kywalh** [comment]
At what time did you commit ?
I just built the last commits at 14:36...

**Comment by Davud2020** [comment]
I have today's late morning green notification. "Time and/or Timezone change on pump"
AAPS commit was Jan 22, 2020 , f5af60712520eedfe7fc382a9b06a64f439fc46e
![TimeZone](https://user-images.githubusercontent.com/48062504/73200588-60b98880-4137-11ea-9cb2-3c57839dba3a.jpg)
[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4118621/AndroidAPS.zip)

**Comment by vanelsberg** [comment]
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

Unexpected Time and/or Timezone ....
Had seen this message only one or two times until updating to V0.2 release.
Now getting this message about once a day (around 00:00h?).
Logs included

![Screenshot_20200127-001829_AndroidAPS](https://user-images.githubusercontent.com/45144129/73319722-85982380-423d-11ea-8352-8e93923b910e.jpg)
[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4125688/AndroidAPS.zip)
[AndroidAPS._2020-01-28_00-00-00_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4125718/AndroidAPS._2020-01-28_00-00-00_.2.zip)

**Comment by vanelsberg** [comment]
And again....
About at the same time of the day.
I would think this my phone scheduled time sync with the network?

[AndroidAPS_LOG_1580338904238.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4131498/AndroidAPS_LOG_1580338904238.log.zip)
![Screenshot_20200130-000126_AndroidAPS](https://user-images.githubusercontent.com/45144129/73408541-d753b300-42fc-11ea-8b65-12edf29fcc8c.jpg)

**Comment by vanelsberg** [comment]
Additional remark to my previous post of 30/01

### Observation:
Starting with the V0.2 release build I am seeing "Time and/or Timezone change on pump" notification *daily and always at 00:00 AM*

(On previous builds I can not remember / did not notice seeing)

**Comment by dar-kod** [comment]
For almost 3 days of using Omnipod 0.2 I'm getting "Time and/or Timezone change on pump" notifications many times per day, very soon after I close notification. Attached screenshots are from 11 February and last is after midnight next day. And logs are from this date also.
[AndroidAPS._2020-02-11_00-00-00_.0[1].zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4189148/AndroidAPS._2020-02-11_00-00-00_.0.1.zip)
[AndroidAPS._2020-02-11_00-00-00_.1[1].zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4189150/AndroidAPS._2020-02-11_00-00-00_.1.1.zip)
[AndroidAPS._2020-02-11_00-00-00_.2[1].zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4189152/AndroidAPS._2020-02-11_00-00-00_.2.1.zip)
[AndroidAPS._2020-02-11_00-00-00_.3[1].zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4189155/AndroidAPS._2020-02-11_00-00-00_.3.1.zip)
[AndroidAPS._2020-02-11_00-00-00_.4[1].zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4189157/AndroidAPS._2020-02-11_00-00-00_.4.1.zip)
![Screenshot_20200211-120055_AndroidAPS 1](https://user-images.githubusercontent.com/24446806/74290159-48e62500-4d31-11ea-9f19-185623da4f1f.jpg)
![Screenshot_20200211-172528_AndroidAPS 1](https://user-images.githubusercontent.com/24446806/74290193-674c2080-4d31-11ea-886b-dd1b72975566.jpg)
![Screenshot_20200211-182429_AndroidAPS 1](https://user-images.githubusercontent.com/24446806/74290208-759a3c80-4d31-11ea-9d92-cdebf3d0fb94.jpg)
![Screenshot_20200212-001409_AndroidAPS 1](https://user-images.githubusercontent.com/24446806/74290231-8480ef00-4d31-11ea-8661-baa43921c71a.jpg)

**Comment by Kaivish** [comment]
Got this timezone issue tonight arount 00.00.58.
Prior to that aaps restarted by itself aroint 23.36 or 23.56. Don't know how or why. Batt. Optimizations are off for aaps. This caused the pump suspended issue resulting in a bad hypo in the middle of the night for several hours. When pump was suspended for 4.5 hrs, on pod tab it showed last connected 4.5hrs ago, tapping refresh connected to pod and got out of pod suspended state and loop started again. 
I guess this issue should get higher priority and be fixed. 


[AndroidAPS_LOG_1582515940110.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4243055/AndroidAPS_LOG_1582515940110.log.zip)

**Comment by Kaivish** [comment]
Uploading logs. Same time zone notifications. Pump not suspended but in logs, there is mentions of pump suspended. Not so good at understanding the logs but it all at beginning of the logs
[AndroidAPS_LOG_1582931921452.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4269592/AndroidAPS_LOG_1582931921452.log.zip)

**Comment by andyrozman** [comment]
It seems that we have 2 issues here. One is time change on midnight, and one are other time changes... I fixed the problem 1, and added a lot more of debug for he second problem... I also added functionality to disable Time changes.

This changes will be in 0.3

**Comment by mick711** [comment]
I can upload m'y log files this Time change appen lot of time all days with 0.2

**Comment by teleriddler** [comment]
**Version:  2.7-omnipod-0.3
Build:      EROS_0.3-2020.03.16-10:35
Flavor: fulldebug
Nightscout version: 13.0.1
Engineering mode enabled
TIME OF EVENT:  16.3.2020 - 17:31:15**

Timezone message appeared again yesterday after updating to version 0.3.  

At 17:31 I was visiting my doctors office that has no cell service (thick walls in the basement of the building) but they do have wifi.  It came as I left the office which I am assuming was when my phone switched from wifi connection back to the cellular network, which I imagine would trigger the cell service checking and setting my phones time to be in sync with the cell tower/service time.   

Just an idea of what might be happening in this case.

[AndroidAPS_LOG_1584436245344.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4342532/AndroidAPS_LOG_1584436245344.log.zip)

**UPDATE:**  Just happened again as I left my house to walk my dog (IE left home wifi, went to cellular network) and when I returned (IE, home wifi connected again) I received the timezone update notification.

**TIME OF EVENT:  17.3.2020 - 11:44:20**

[AndroidAPS_LOG_1584442050230.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4343024/AndroidAPS_LOG_1584442050230.log.zip)

**Comment by vanelsberg** [comment]
> time change on midnight,

Confirming. Haven seen any "time change" alerts around midnight with V0.3. 
Tnx!

**Comment by bartsopers** [comment]
@teleriddler @andyrozman @vanelsberg does this issue still exist?

**Comment by vanelsberg** [comment]
Have not seen this for a long time (since repair in 0.3?)

**Comment by bartsopers** [comment]
Closing this as it seems to be working properly now.
