### ISSUE TITLE
add progress bar during pairing and priming

### ISSUE THREAD

**Issue by Kywalh** [AAPS-Omnipod/AndroidAPS-OLD#57]
it would be great to see the progress of the pod pairing and priming steps.
Indeed, the turning wheel doesn't reflect the real status since it can mislead to a frozen state...

**Comment by bartsopers** [comment]
Won't fix this because there is no reliable way to show progress, as every step in the 'init pod' process actually consists of multiple commands. The spinner will never 'freeze': it will always display an error in case of failure.

**Comment by mountrcg** [comment]
the progress bar for priming of a new pod in Loop is very accurate timewise. The priming bar only appears after successfull pairing. So the second step seems to be really well defined timewise.
