### ISSUE TITLE
New version available notification frequently pops up

### ISSUE THREAD

**Issue by Kywalh** [AAPS-Omnipod/AndroidAPS-OLD#58]
![Screenshot_20200119-131230](https://user-images.githubusercontent.com/28366579/72680738-7d154f80-3abd-11ea-9215-b5d294544545.jpg)

**Comment by killakitty69** [comment]
I haven't gotten a treatment in an hour.  Pressing Run Now on Loop tab says No Change Requested. 

![Screenshot_AndroidAPS_20200119-141344](https://user-images.githubusercontent.com/46402601/72686953-83102e00-3ac7-11ea-8341-f7244c6cb0ca.png)

**Comment by bartsopers** [comment]
Fixed by @andyrozman in afc07c5117021fac9c5a93bbdb4dc7c3a1e70625
