### ISSUE TITLE
Mismatch of insulin delivery after stopping bolus

### ISSUE THREAD

**Issue by Kywalh** [AAPS-Omnipod/AndroidAPS-OLD#61]
test: stopping a 1u bolus in progress... 
Stopped at 5 clicks and 0.40u reported instead of 0.25u even if response time between STOP pressed and pod confirmation bip was quite short.

**Comment by bartsopers** [comment]
Fixed in 93e7eb518f18793a29d9af3dcfe2bac67d44142a
