### ISSUE TITLE
Init Pod & Deactivate Pod buttons are enabled when RileyLink is not initialized yet

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#66]
The Init Pod & Deactivate Pod buttons in the Pod Management menu are enabled when the RileyLink is not connected yet. This can cause commands to be sent during RileyLink setup, which can possibly mess things up.

The buttons should be disabled until the RL is connected.

**Comment by avicorp** [comment]
Hi can i take the task? it looks like a nice place to start contributing.
