### ISSUE TITLE
POD Tab shows impossible basal rate

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#68]
AndroidAPS 2.6-omnipod0.2-SNAPSHOT
Build EROS_0.1-10-g68678023d-20 20.01.22-09:21 fullrelease

**POD tab shows Base basal rate as 0.27 U/h**
Which is strange as OmniPod basal rates are always a multiple of 0.05U
(Overview showed actual basal rate as being 0.30 U/h)

Remarks:
* Not sure why "SET PROFILE" is show. Active profile was successfully set.
* Could not reproduce this. Will add comment when I see this again.

Screenshot:
![image](https://user-images.githubusercontent.com/45144129/73028690-56954280-3e36-11ea-8e3a-85a753f47507.png)

**Comment by andyrozman** [comment]
This is fixed (will be released with 0.3). Similar than error #71
