### ISSUE TITLE
Filter selection on the Pod History view is not working.

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#69]
AndroidAPS 2.6-omnipod0.2-SNAPSHOT
Build EROS_0.1-10-g68678023d-20 20.01.22-09:21 fullrelease

In the Pod History view the option to filter by type is not (yet?) working. When I select a specific "Type" from the dropdown box (top left of the screen, f.i. Type: Boluses) I still get to see the full list of history items.

Expected behavior:
When selecting a filter "Type" the History view shows only history items for the selected type.

**Comment by andyrozman** [comment]
This is not implemented yet.

**Comment by vanelsberg** [comment]
Tx!

**Comment by andyrozman** [comment]
Fixed on dev, will be released with 0.3
