### ISSUE TITLE
Bolus administered does not show in increments of 0.05

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#71]
AndroidAPS 2.6-omnipod0.2-SNAPSHOT
Build EROS_0.1-18-g36128c400-2020.01.25 fullrelease

## Problem (minor)
OmniPod bolus is in Nx0.05 units.
Om administering a bolus, progress bar also shows in units of 0.05. On the POD tab (and also under POD history) boluses are only reported in increment of 0.1U.
(Basel rates are OK, showing in multiple unit of 0.05))

## Example:
*From overview, a manual bolus of 0.25 is given (pop-up confirms as "Bolus: 0.25U")
*On OK, the progress bar confirms delivering 0.25U
*POD tab reports: "Last bolus: 0,3 U (Now)"
*Pod History reports: "Set Bolus, 0.3 U, CH=0.0 g"

**Comment by vanelsberg** [comment]
(Similar than error #71)

Found it: Looks like the 0.27U reported by AAPS was the result of doing a profile switch to 110% while current profile rate was 0.25U.
I think the actual basel rate on the pod was set to 0,30U/h (or maybe 0.25U/h?)

### Repro
While current basal rate in Profile is at 0.25U/h
Switch current profile to 110% 
POD tab shows 1.1 * 0.25 = 0.27 U/h

### Screenshot:
![Screenshot_20200122-233935_AndroidAPS](https://user-images.githubusercontent.com/45144129/73593304-f459d300-4502-11ea-8ea3-1abf301ef451.jpg)

**Comment by andyrozman** [comment]
This is fixed (will be released with 0.3)
