### ISSUE TITLE
Last connection in Omnipod tab incorrectly updated to 'Now' when communication fails

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#77]
Please see below screenshots. In the first screenshot, you can see that the last two communication attempts failed. However, in the second screenshot, you can see that the Omnipod tab incorrectly displays 'Now' in the 'Last connection' field.
![Screenshot_20200127-103123](https://user-images.githubusercontent.com/15631208/73163934-3a70fa00-40f1-11ea-8b1b-26666a47a5b9.png)
![Screenshot_20200127-103128](https://user-images.githubusercontent.com/15631208/73163944-3d6bea80-40f1-11ea-8796-1f4ef2b654e8.png)

**Comment by andyrozman** [comment]
@bartsopers is that fixed?
