### ISSUE TITLE
Failed to activate pod with old v1 Eros settings

### ISSUE THREAD

**Issue by marksieminski** [AAPS-Omnipod/AndroidAPS-OLD#78]
Reporting bugs
--------------
- exported AAPS settings with connected pod to hard drive. Disconnected pod. Uninstalled Eros v1 and installed Eros v2.

Imported settings and noted pod address still available. Reset pod and tried to pair. Pod communication failed. Reset Riley link and reset phone, pod communication failed.

Uninstalled and reinstalled v2 with no settings imported. Connected Riley link and tried to pair pod. Pod failed.

- Eros version 2
- phone pixel 3 xl
- android 9
- failed to grab log.
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by marksieminski** [comment]
![Screenshot_20200128-190322](https://user-images.githubusercontent.com/40119456/73318028-24a12900-4206-11ea-91ab-a7a1eb2263b5.png)

**Comment by andyrozman** [comment]
Seems like one of... You should never export settings while Pod is running... Closing
