### ISSUE TITLE
Initial one-time failure at Pod Init / Pair & Prime

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#79]
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

### Problem:
While activating a new pod I got an error (lost the screenprint) just after filling the Pod, starting the pairing & priming sequence (see log at 00:34:11?
Fortunately, after clicking the retry button, Pod initialisation sequence was smooth and fully succesful.

### Additional info:
_(Edit: Looks like ISSUE Priming a pod sometimes fails #60?)_
From the logs it looks like a comms failure. Can not explain as generally I have very steady RL/Pod connections with virtually no failures on the UI (other then by my own doing).
RL was near/touching the Pod.

FYI: going back in the log you will find lots of comms failures:
1. Before starting a Pod de-activation I walked downstairs without taking the phone.
2. Tried "exit"-ing AAPS which resulted in a "Uncaught exception crashing app" at about 00:43 (see issue #81 reported).

[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4125764/AndroidAPS.zip)
[AndroidAPS._2020-01-28_00-00-00_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4125765/AndroidAPS._2020-01-28_00-00-00_.2.zip)

**Comment by bartsopers** [comment]
Thank for your report. This is normal behavior which can sometimes occur. If you ever experience a situation in which the retry button repeatedly doesn't work, which forces you to discard your pod, please report it under #60.

**Comment by vanelsberg** [comment]
Sure, Thanks.
In this particular case I think the driver handled the problem and was able to succesfully activate the Pod. Nice!
