### ISSUE TITLE
Screen layout caps text area while executing Pod de-activation

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#80]
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

### Problem:
Screen layout caps text area while executing Pod de-activation.
### Hardware:
Samsung S7, Screen resolution 1920x1080 (FHD)

### Additional info
See screen prints below:

![Screenshot_20200129-002847_AndroidAPS](https://user-images.githubusercontent.com/45144129/73321157-e295d880-4241-11ea-8660-8a5c34398407.jpg)

![Screenshot_20200129-002906_AndroidAPS](https://user-images.githubusercontent.com/45144129/73321167-e6295f80-4241-11ea-8a63-a132feab31ab.jpg)

**Comment by andyrozman** [comment]
This is fixed (will be released with 0.3)

**Comment by andyrozman** [comment]
Duplicate of #51
