### ISSUE TITLE
"Uncaught exception crashing app" when trying to exit application through UI

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#81]
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

### Problem:
Application crashed unexpectedly when trying to exit through the UI "exit" menu option.
As a result  screen went complete "black", then after some time I was presented with the Close/Wait option.

Solved by choosing "Close" and the restarting AAPS.
No problems from there on.

### Additional info
See log at about
`00:43:23.176 [main] E/CORE: [MainApp.lambda$onCreate$0():139]: Uncaught exception crashing app
`
[AndroidAPS._2020-01-28_00-00-00_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4125833/AndroidAPS._2020-01-28_00-00-00_.2.zip)
[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4125834/AndroidAPS.zip)

**Comment by andyrozman** [comment]
This is core problem, not related to driver, so we won't be fixing this...
