### ISSUE TITLE
POD MGMT -> Deactivate pod -- UI issue (Omnipod 0.2)

### ISSUE THREAD

**Issue by dar-kod** [AAPS-Omnipod/AndroidAPS-OLD#85]
Instruction text and "Deactivate Pod" is not completely visible in Samsung Galaxy s7 edge, Android 8.0.0, Android Omnipod 0.2. Also, the similar or same issue happens by the activation of a pod. I may upload screenshots, if needed, next time.

![Screenshot_20200212-200445_AndroidAPS](https://user-images.githubusercontent.com/24446806/74382838-6200db80-4dee-11ea-8261-756e73335524.jpg)

![Screenshot_20200212-200509_AndroidAPS](https://user-images.githubusercontent.com/24446806/74382725-35e55a80-4dee-11ea-9a78-d4946a60e402.jpg)

**Comment by andyrozman** [comment]
Duplicate #80. Closing...
