### ISSUE TITLE
Pod failure after 6 hours (screamer) 

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#88]
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

**Problem:**
Pod failed with screamer.
(According to Pod history right after a set + cancle  Temporary Basel)

**Additional info:**
Could not deactivate Pod. Needed Reset Pod.

Possible causes:
- Canula occlusion?: The Pod was on a site that caused occlusion errors before.
Had been looking into unexplainable BG raising hours before.
- Comm errors?: Just minutes before the screamer I walked way from RL far enough to introduce minor communication errors.

See logfile:
I think the Pod was streaming at about 00:12:22
Tried deactivating at 00:15:25.212 (failed, Pod was screaming)

[AndroidAPS_LOG_1581722265917.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4208336/AndroidAPS_LOG_1581722265917.log.zip)

**Comment by bartsopers** [comment]
Unfortunately, these logs don't contain any information about the pod fault. The logs only contain info about the pod fault if commands have been exchanged after the pod fault occurred. Apparently, that's not the case here, which aligns with the fact that deactivation apparently failed.
As I don't know what pod fault it was, I will unfortunately close this issue without being able to fix anything.
