### ISSUE TITLE
Multiple commands fail in a row due to 'Communication failed' error

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#92]
Sometimes, multiple commands fail in a row due to 'Communication failed' errors.

**NOTE: Please comment to this issue if you also experience this issue. Please only do so if you can provide ALL below information:**
- **Logs**
- **A screenshot of the Pod History screen (on the Omnipod tab, press Pod Mgmt and then Pod History)**
- (in case you know) **Which steps you took to fix this issue** (resetting RL, restarting AAPS, turning off/on BT, rebooting phone?)

**Comment by biwhite** [comment]
Experienced a pump suspended around midnight.  That eventually was rectified near 2am.
Trying to bolus later that day around 19:30, had numerous communication errors.  Again eventually rectified after a bunch of attempts.

Normally try AAPS restart, bluetooth toggles.  Reset RL configuration etc.
Logs for the past day attached, as well as a few screenshots from the failed bolus.
Screenshot from the overnight failure as well, showing when it started failing when you can see it went back onto default profile setting on the blue graph.

![WhatsApp Image 2020-02-17 at 08 45 33](https://user-images.githubusercontent.com/3225320/74687950-d57b6200-51cd-11ea-8aed-59f75fed2c30.jpeg)

![WhatsApp Image 2020-02-17 at 19 41 40](https://user-images.githubusercontent.com/3225320/74687665-f099a200-51cc-11ea-82e7-b35937898b7d.jpeg)
![WhatsApp Image 2020-02-17 at 19 42 42](https://user-images.githubusercontent.com/3225320/74687669-f2fbfc00-51cc-11ea-8e27-b69cc9e1377b.jpeg)
![WhatsApp Image 2020-02-17 at 19 42 58](https://user-images.githubusercontent.com/3225320/74687672-f4c5bf80-51cc-11ea-940b-06442f4bd7a4.jpeg)
[AndroidAPS._2020-02-17_19-49-30_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4216288/AndroidAPS._2020-02-17_19-49-30_.0.zip)
[AndroidAPS._2020-02-16_12-58-58_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4216305/AndroidAPS._2020-02-16_12-58-58_.1.zip)
[AndroidAPS._2020-02-16_12-58-58_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4216306/AndroidAPS._2020-02-16_12-58-58_.2.zip)
[AndroidAPS._2020-02-17_01-55-17_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4216307/AndroidAPS._2020-02-17_01-55-17_.0.zip)
[AndroidAPS._2020-02-17_01-55-17_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4216309/AndroidAPS._2020-02-17_01-55-17_.1.zip)
[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4216310/AndroidAPS.log)

**Comment by biwhite** [comment]
Pod history screenshots, overnight pump unreachable stuff, and this evening communication failure.
![WhatsApp Image 2020-02-17 at 21 49 42](https://user-images.githubusercontent.com/3225320/74688601-e927c800-51cf-11ea-8076-358c1c5d1d84.jpeg)
![WhatsApp Image 2020-02-17 at 21 52 28](https://user-images.githubusercontent.com/3225320/74688602-ea58f500-51cf-11ea-8401-ad59a44c3750.jpeg)
![WhatsApp Image 2020-02-17 at 21 52 44](https://user-images.githubusercontent.com/3225320/74688603-eaf18b80-51cf-11ea-82ed-4695026cab9d.jpeg)

**Comment by bartsopers** [comment]
[AndroidAPS_LOG_1580726947481.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4239038/AndroidAPS_LOG_1580726947481.log.zip)
![Screenshot_20200203-114839](https://user-images.githubusercontent.com/15631208/75089609-deb45800-555a-11ea-9080-2028f2dc8e0e.png)

**Comment by bartsopers** [comment]
@biwhite can you please add 1 screenshot and the corresponding log? Please refer to my example above.

**Comment by avivaac** [comment]
![IMG-20200222-WA0010](https://user-images.githubusercontent.com/52380331/75089799-7ebab300-5554-11ea-84fd-87f40c719c6e.jpg)
![IMG-20200222-WA0008](https://user-images.githubusercontent.com/52380331/75089800-7f534980-5554-11ea-8e90-07d04d224988.jpg)
![IMG-20200222-WA0009](https://user-images.githubusercontent.com/52380331/75089803-80847680-5554-11ea-82e9-d56aef5acabe.jpg)
![IMG-20200222-WA0007](https://user-images.githubusercontent.com/52380331/75089807-811d0d00-5554-11ea-837f-97dbda871a3d.jpg)

**Comment by avivaac** [comment]
[AndroidAPS._2020-02-22_07-49-00_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4239047/AndroidAPS._2020-02-22_07-49-00_.0.zip)

**Comment by Kaivish** [comment]
Getting a lot of communication failed when getting pod status. But setting tbr is apparently working.
Sending all the logs when these issues happened. 
![IMG_20200225_211209](https://user-images.githubusercontent.com/41928579/75283813-d33f8600-5813-11ea-8824-f03b11ad2b94.jpg)
![IMG_20200225_211154](https://user-images.githubusercontent.com/41928579/75283818-d5a1e000-5813-11ea-9714-8674f818eecc.jpg)
![IMG_20200225_211131](https://user-images.githubusercontent.com/41928579/75283822-d76ba380-5813-11ea-87ee-787db37f51f5.jpg)
![IMG_20200225_210914](https://user-images.githubusercontent.com/41928579/75283828-d9356700-5813-11ea-961a-44f10a4ce663.jpg)
[AndroidAPS_LOG_1582660981238.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251964/AndroidAPS_LOG_1582660981238.log.zip)
[AndroidAPS._2020-02-25_13-14-24_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251965/AndroidAPS._2020-02-25_13-14-24_.0.zip)
[AndroidAPS_LOG_1582641359858.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251966/AndroidAPS_LOG_1582641359858.log.zip)
[AndroidAPS._2020-02-25_11-57-10_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251967/AndroidAPS._2020-02-25_11-57-10_.1.zip)
[AndroidAPS._2020-02-25_13-41-23_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251968/AndroidAPS._2020-02-25_13-41-23_.0.zip)
[AndroidAPS._2020-02-25_14-00-55_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251969/AndroidAPS._2020-02-25_14-00-55_.0.zip)
[AndroidAPS._2020-02-25_14-02-24_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251970/AndroidAPS._2020-02-25_14-02-24_.0.zip)
[AndroidAPS._2020-02-25_13-08-04_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251971/AndroidAPS._2020-02-25_13-08-04_.0.zip)
[AndroidAPS._2020-02-25_13-34-18_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251972/AndroidAPS._2020-02-25_13-34-18_.0.zip)
[AndroidAPS._2020-02-25_11-51-14_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251973/AndroidAPS._2020-02-25_11-51-14_.0.zip)
[AndroidAPS._2020-02-25_11-50-19_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4251974/AndroidAPS._2020-02-25_11-50-19_.0.zip)



In rl stats, it said bt error. Bt off and on. Refresh status, nothing. Bt off, restart aaps, bt on. Refresh then said connected to rl, but still comm failure. But tbrs seem to be working though, at least shown on gui.

**Comment by vanelsberg** [comment]
Also seeing this on at least at two occasions.
First time I just ignored thinking I'd gone out of range. 

Second time at night with unexpected high BG when waking in the morning.
Surprisingly no alerts had been fired. Only noticed when trying to bolus which gave me the "communication failed/Mute/OK" pop-up.

Solved by toggling BT and force-kill/restarting AAPS

Unfortunately I lost the log's :-|
(Will monitor and post log's on when the problem reoccurs)

**Comment by vanelsberg** [comment]
More of the same?
Log files export with 10 minutes after the incident:

[AndroidAPS_LOG_1585300225141.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4398366/AndroidAPS_LOG_1585300225141.log.zip)
[AndroidAPS_LOG_1585088381269.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4398367/AndroidAPS_LOG_1585088381269.log.zip)
[AndroidAPS_LOG_1585180912298.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4398368/AndroidAPS_LOG_1585180912298.log.zip)

**Comment by mistermintsgh** [comment]
I'm having what I think is a very similar problem. Oddly, it's only really started to happen in the last couple of weeks (that I noticed).

If I don't manually hit refresh at least every 60-90 minutes the pod and RL will eventually lose connection. The status page will tell me that everything looks connected, but the pod history tells me communication has failed.

This is a particular problem over longer periods where I'm unable to interact with the phone (e.g. while sleeping) and I often wake up either high or low depending on what I've been doing if AAPS is unable to adjust my TBR.

Screen shot of last night's communication failure attached. Will also upload logs when I can get to a computer
![Screenshot_20200509-091523_AndroidAPS](https://user-images.githubusercontent.com/42671801/81468563-2fd9fc80-91d8-11ea-8bef-f6d4d4a81bb1.jpg)

**Comment by mistermintsgh** [comment]
Logs attached for communication error overnight. Failure takes place around 0345hrs

[AndroidAPS._2020-05-14_00-00-13_.0[1].zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4627361/AndroidAPS._2020-05-14_00-00-13_.0.1.zip)

**Comment by bartsopers** [comment]
Probably caused by a lost RL connection. Created #150 for implementing an auto-reconnect mechanism.
