### ISSUE TITLE
More times bolus attempt and screamer with the code number 049

### ISSUE THREAD

**Issue by Davud2020** [AAPS-Omnipod/AndroidAPS-OLD#93]
I adjusted a new pod and everything went as it should. I had to give bolus for my breakfast but it didn't occur. So I tried a few times or more and then I had this screamer error code 049.
[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4230077/AndroidAPS.zip)

**Comment by bartsopers** [comment]
Can you please also provide the preceding log? This log only goes back until about 1 minute before executing the bolus, as you probably just restarted AAPS.

**Comment by Davud2020** [comment]
[AndroidAPS._2020-02-19_10-35-27_.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4237993/AndroidAPS._2020-02-19_10-35-27_.zip)

**Comment by bartsopers** [comment]
Closing this for now as this was probably in 0.1 or 0.2. We did a lot of improvements since then. Please open a new issue of you still experience this issue after the upcoming 0.4 release.
