### ISSUE TITLE
Wrong ui wording in pod stats page

### ISSUE THREAD

**Issue by Kaivish** [AAPS-Omnipod/AndroidAPS-OLD#94]
Testing ui and didn't pair to rl yet. Tapping on rl stats or pod mgmt or pulse buttons asks to activate medtronic pump. I think it should say omnipod pump. 
Guessing its nothing critical, just ui improvement. 

![Screenshot_20200220_232509_info nightscout androidaps](https://user-images.githubusercontent.com/41928579/74986701-dfa19880-5439-11ea-856d-63c3f77a2ac2.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by andyrozman** [comment]
Fixed in 0.3
