### ISSUE TITLE
Incorrect info from SMS commands and pump read status failed

### ISSUE THREAD

**Issue by Kaivish** [AAPS-Omnipod/AndroidAPS-OLD#96]
There are some wrong info as to iob in sms commands and pump status read says failed. Dont know why, but remote bolusing works fine even if pump status says failed. 
Attaching screenshot, all smses were sent within a minute or so timeframe. 

![Screenshot_20200223_214556](https://user-images.githubusercontent.com/41928579/75136222-4518b200-56e4-11ea-908b-28778e5bf376.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by andyrozman** [comment]
Please report this on main AAPS. This is not pump driver related.
