### ISSUE TITLE
Aaps restarts by itself. Get a notification of no pod active and pump goes suspended state. Critical issue

### ISSUE THREAD

**Issue by Kaivish** [AAPS-Omnipod/AndroidAPS-OLD#98]
Something happened today at around pretty much same time. Around 23 is. Yesterday iy was logged at 22.57, today the same thing logged at 23.19
Aaps restarted by itself, don't know why. But start is logged in careportal, ns. When started again, it gives a notification of no active pod and it goes in suspended pump state. 
Could not get the logs in time yesterday, but today i managed to grab them. This seems to me  to be a critical issue. 
Attaching logs and screens. 

[AndroidAPS_LOG_1582515940110.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4247274/AndroidAPS_LOG_1582515940110.log.zip)

![IMG_20200224_233828](https://user-images.githubusercontent.com/41928579/75199077-71731380-5762-11ea-9983-6a882e0011e7.jpg)
![IMG_20200224_233808](https://user-images.githubusercontent.com/41928579/75199096-79cb4e80-5762-11ea-8e0d-e929c0050f36.jpg)
![IMG_20200224_233706](https://user-images.githubusercontent.com/41928579/75199118-86e83d80-5762-11ea-902f-d614a70d866a.jpg)
![IMG_20200224_233726](https://user-images.githubusercontent.com/41928579/75199147-92d3ff80-5762-11ea-97e2-62f294d6e70e.jpg)

Seems upon restart, only rl is reconnected and checked, not pod. Could it be made to connect to rl AND pod upon restart, this would probably sort out the issue. 
Still don't get it as to why aaps restarted. Battery optimization is off for aaps and no other app running which will close it. 

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by Kaivish** [comment]
Same thing today again around same time
Timeline is 00.19
[AndroidAPS_LOG_1582680864281.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4253668/AndroidAPS_LOG_1582680864281.log.zip)

New logs

[AndroidAPS_LOG_1582660981238.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257459/AndroidAPS_LOG_1582660981238.log.zip)
[AndroidAPS._2020-02-25_13-14-24_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257460/AndroidAPS._2020-02-25_13-14-24_.0.zip)
[AndroidAPS_LOG_1582641359858.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257461/AndroidAPS_LOG_1582641359858.log.zip)
[AndroidAPS._2020-02-25_11-57-10_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257462/AndroidAPS._2020-02-25_11-57-10_.1.zip)
[AndroidAPS_LOG_1582680864281.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257463/AndroidAPS_LOG_1582680864281.log.zip)
[AndroidAPS._2020-02-25_13-41-23_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257464/AndroidAPS._2020-02-25_13-41-23_.0.zip)
[AndroidAPS._2020-02-25_14-00-55_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257465/AndroidAPS._2020-02-25_14-00-55_.0.zip)

**Comment by Kaivish** [comment]
Adding more logs
[AndroidAPS._2020-02-25_00-00-00_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257976/AndroidAPS._2020-02-25_00-00-00_.1.zip)
[AndroidAPS._2020-02-25_00-00-00_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257977/AndroidAPS._2020-02-25_00-00-00_.2.zip)
[AndroidAPS._2020-02-25_00-00-00_.3.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257978/AndroidAPS._2020-02-25_00-00-00_.3.zip)
[AndroidAPS._2020-02-25_00-00-00_.4.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257979/AndroidAPS._2020-02-25_00-00-00_.4.zip)
[AndroidAPS._2020-02-25_00-00-00_.5.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257980/AndroidAPS._2020-02-25_00-00-00_.5.zip)
[AndroidAPS._2020-02-25_00-00-00_.6.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257981/AndroidAPS._2020-02-25_00-00-00_.6.zip)
[AndroidAPS._2020-02-25_00-00-00_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257982/AndroidAPS._2020-02-25_00-00-00_.0.zip)
[AndroidAPS._2020-02-24_23-19-02_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257983/AndroidAPS._2020-02-24_23-19-02_.1.zip)
[AndroidAPS._2020-02-24_23-19-02_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257984/AndroidAPS._2020-02-24_23-19-02_.0.zip)
[AndroidAPS._2020-02-25_21-01-57_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257985/AndroidAPS._2020-02-25_21-01-57_.0.zip)
[AndroidAPS._2020-02-25_21-01-57_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257986/AndroidAPS._2020-02-25_21-01-57_.1.zip)
[AndroidAPS._2020-02-25_21-01-57_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257987/AndroidAPS._2020-02-25_21-01-57_.2.zip)
[AndroidAPS._2020-02-25_21-01-57_.3.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257988/AndroidAPS._2020-02-25_21-01-57_.3.zip)
[AndroidAPS._2020-02-26_00-36-08_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257989/AndroidAPS._2020-02-26_00-36-08_.0.zip)
[AndroidAPS._2020-02-26_00-36-08_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257990/AndroidAPS._2020-02-26_00-36-08_.1.zip)
[AndroidAPS._2020-02-26_00-36-08_.10.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257991/AndroidAPS._2020-02-26_00-36-08_.10.zip)
[AndroidAPS._2020-02-26_00-36-08_.11.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257992/AndroidAPS._2020-02-26_00-36-08_.11.zip)
[AndroidAPS._2020-02-26_00-36-08_.12.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257993/AndroidAPS._2020-02-26_00-36-08_.12.zip)
[AndroidAPS._2020-02-26_00-36-08_.2.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257994/AndroidAPS._2020-02-26_00-36-08_.2.zip)
[AndroidAPS._2020-02-26_00-36-08_.3.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257995/AndroidAPS._2020-02-26_00-36-08_.3.zip)
[AndroidAPS._2020-02-26_00-36-08_.4.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257996/AndroidAPS._2020-02-26_00-36-08_.4.zip)
[AndroidAPS._2020-02-26_00-36-08_.5.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257997/AndroidAPS._2020-02-26_00-36-08_.5.zip)
[AndroidAPS._2020-02-26_00-36-08_.6.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257998/AndroidAPS._2020-02-26_00-36-08_.6.zip)
[AndroidAPS._2020-02-26_00-36-08_.7.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4257999/AndroidAPS._2020-02-26_00-36-08_.7.zip)
[AndroidAPS._2020-02-26_00-36-08_.8.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4258001/AndroidAPS._2020-02-26_00-36-08_.8.zip)
[AndroidAPS._2020-02-26_00-36-08_.9.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4258002/AndroidAPS._2020-02-26_00-36-08_.9.zip)

**Comment by Kaivish** [comment]
Still on ver0.2. Got the pump unreacheable issue and pump suspended after that.
Time line is 10.53 where pump unreacheable happened. 
[AndroidAPS_LOG_1583057510109.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4271630/AndroidAPS_LOG_1583057510109.log.zip)

**Comment by andyrozman** [comment]
@Kaivish This is no longer relevant right? You found the problem.

**Comment by Kaivish** [comment]
Well I thought so, but happened a couple of times again. Couldn't get the logs. Trying to figure out if its related to my phone

**Comment by Kaivish** [comment]
Didn't see this behaviour for a couple of months now.
